dtb-$(CONFIG_ARCH_P660)		+= hisi_p660_evb.dtb
dtb-$(CONFIG_ARCH_P660)         += hisi_p660_evb_pangea.dtb
dtb-$(CONFIG_ARCH_P660)		+= hip05-d02.dtb
dtb-$(CONFIG_ARCH_P660)		+= hip05-2p1s.dtb hip05-s01.dtb hip05-lemon.dtb
dtb-$(CONFIG_ARCH_Hi1610)	+= hisi_hi1610.dtb hisi_hi1610_fpga.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
