obj-$(CONFIG_FB_HISILICON) += hisiliconfb.o

hisiliconfb-y := hisi_drv.o hisi_hw.o hisi_accel.o hisi_cursor.o hisi_chip.o
hisiliconfb-y += hisi_mode.o hisi_power.o

hisiliconfb-objs := $(hisiliconfb-y)
